services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/project_tracker_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=tracker_app_user
      - SPRING_DATASOURCE_PASSWORD=your_secure_production_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_ADDRESS=0.0.0.0
    depends_on:
      - mysql
    networks:
      - vimadimension-network
    restart: unless-stopped
    volumes:
      - app-logs:/app/logs

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
      - MYSQL_DATABASE=project_tracker_db
      - MYSQL_USER=tracker_app_user
      - MYSQL_PASSWORD=your_secure_production_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
    networks:
      - vimadimension-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
  mysql_logs:
  app-logs:

networks:
  vimadimension-network:
    driver: bridge
